### ISSUE TITLE
SetParam error when value setting to is empty.

### ISSUE THREAD

**Issue by miketonguk** [cake-contrib/Cake.MsDeploy#16]
Sometimes I want to set the value of a set param to the empty string. i.e. In some environments certain config doesn't apply and so should be set to nothing. However the code in SetParameter omits the value part of the command line when the value is empty or whitespace. 

```
if (!string.IsNullOrWhiteSpace(Value))
              sb.AppendFormat(",value=\"{0}\"", Value);
```

This might have been OK, but MSDeploy mandates that it should be present.

`Error: The -setParam argument must have the 'value' parameter specified.`

Please can you remove this check to allow value="" to be added to the command line.

**Comment by miketonguk** [comment]
Well it turns out setting value="" on the commandline doesn't work either as msdeploy requires that the value is not empty string.

**Comment by louisfischer** [comment]
@miketonguk That was part of the check because MsDeploy does not allow an empty string. That is why the check is there and ignores it if it is empty

**Comment by louisfischer** [comment]
@miketonguk I would take a pull request if you want to give it a try
