### ISSUE TITLE
Cake Team Collaborator

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.MsDeploy#2]
@louisfischer thank you for inviting the Cake Team to collaborate on this project.  Does that suggest that you are interested in moving this repo into the cake-contrib organisation?

Thanks

**Comment by louisfischer** [comment]
Yes. I wanted to contribute to the cake project. I was going to open a pull request on the cake documentation website to ask this plugin be included in the Add-in section of the site. I read the blog post in August on adding the cake-contribute user and wanted to start it off right.

**Comment by louisfischer** [comment]
@gep13 Issue 203 opened on the cake documentation website for request

https://github.com/cake-build/website/issues/203

**Comment by gep13** [comment]
@louisfischer I have accepted the invitation for the cake-contrib-bot to be a collaborator on this project, however, in order to move this repo to the cake-contrib organisation, I need to be be an admin on both sides.  The easiest way to do this is actually for you to transfer the ownership of the repo to me (gep13 on GitHub).  You can do this through the Settings page on the repo:

![image](https://cloud.githubusercontent.com/assets/1271146/20039469/61f83eb2-a43c-11e6-8d24-341d20be5691.png)

Once that is done, I can transfer it into the cake-contrib organisation, giving you again, full control over the repo.

Let me know how you would like to proceed.  Thanks

**Comment by gep13** [comment]
This has all been completed, so going to go ahead and close this out.

Thanks!
