### ISSUE TITLE
Update icon with new cake-contrib icon

### ISSUE THREAD

**Issue by louisfischer** [cake-contrib/Cake.MsDeploy#20]
Update the Nuget icon with the new cake-contribution icon. See blog post below

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

**Comment by gep13** [comment]
Recommended url is https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png
