### ISSUE TITLE
Update nuspec

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.MsDeploy#3]
To correct the location of the repo, now that it is in cake-contrib.

As an example:

https://github.com/cake-contrib/Cake.MsDeploy/blob/master/nuspec/Cake.MsDeploy.nuspec#L11

**Comment by louisfischer** [comment]
@gep13 I updated the license files but i am not able to create a feature branch. I was getting an access denied error. How do you handle changes for new code for the cake-contrib org repos?
Do I need to fork the repo and create a pull request on my personal account?

**Comment by gep13** [comment]
@louisfischer hmm, that is very strange.  Let me check some things...

It is really up to you.  You should be able to handle it in both ways.

**Comment by gep13** [comment]
@louisfischer  Can you please try again?  Also, can you please list out all the steps that you are following to create the new branch, if it isn't working?  Thanks

**Comment by louisfischer** [comment]
@gep13  The gui tool I was using could not seem to handle it (GitKraken). I pushed the changes from the command line and it worked. So I can make the changes that way. Thanks for looking into it for me. In this case, it was user error...:)

**Comment by gep13** [comment]
@louisfischer could GitKraken still be looking at your old repo?  Before it was moved to cake-contrib?

Glad to hear that you got it working!

**Comment by louisfischer** [comment]
I did check the origin in the repo and it pointed to the new one. GitKraken does not use the .gitconfig file. It uses some other type of authentication. I am not sure what the error below means but I can make changes so that is good for me

![image](https://cloud.githubusercontent.com/assets/1905010/20087770/10444858-a541-11e6-8d44-20a658a9b3e5.png)

**Comment by gep13** [comment]
@louisfischer I saw a request come through from that application to access the organisation.  I am not entirely sure why this is required, and I am hesitant to allow it until I know more.  Seems like you have a path forward though, so we can leave for now.

**Comment by louisfischer** [comment]
@gep13 no problem. I
