### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.MsDeploy#4]
With new AppVeyor project:

https://ci.appveyor.com/project/cakecontrib/cake-msdeploy

**Comment by louisfischer** [comment]
@gep13 Can you grab the status badges off the new build? I can update the readme after that

![image](https://cloud.githubusercontent.com/assets/1905010/20088382/50c461e8-a545-11e6-8119-c6e6a8f0dffc.png)

**Comment by louisfischer** [comment]
Updated badge with 
https://ci.appveyor.com/api/projects/status/github/cake-contrib/Cake.MsDeploy

**Comment by gep13** [comment]
@louisfischer for your information, you should be able to log into ci.appveyor.com, and access the CI Build for Cake.MsDeploy.

**Comment by louisfischer** [comment]
@gep13 cool...Thanks Gary. I will take a look at it
