### ISSUE TITLE
Examples of DbDacFxProvider usage

### ISSUE THREAD

**Issue by granttrevor** [cake-contrib/Cake.MsDeploy#9]
Hi - do you have any examples of DbDacFxProvider usage?

Is this meant to be configured as both a Source and Destination within a MsDeploySettings definition?

thanks.

**Comment by louisfischer** [comment]
@granttrevor  I currently do not have any examples of using the DbDacFx Provider. That is a future documentation feature I would like to incorporate into the project. This plugin is just a wrapper around the MsDeploy cli. It does require a Source and Destination. The parameters will differ depending on the msdeploy provider. Does that help?

**Comment by granttrevor** [comment]
Thanks for the reply @louisfischer  - I will give it a go and let you know how I get on. Cheers
